version: '3.7'
services:
  # api:
  #   container_name: demo_system_api
  #   hostname: api
  #   image: demo-system-api:latest
  #   # platform: linux/amd64
  #   ports:
  #     - '3001:3000'
  #   environment:
  #     MQTT_URL: mqtt://localhost:1883
  #     MQTT_USERNAME: '${MQTT_USERNAME}'
  #     MQTT_PASSWORD: '${MQTT_PASSWORD}'
  #     GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
  #     GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
  #     AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  #     AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
  #     SENDER_EMAIL: '${SENDER_EMAIL}'
  #     SNS_TOPIC_ARN: '${SNS_TOPIC_ARN}'
  mqtt:
    hostname: mqtt
    image: custom-mqtt-server:latest
    platform: linux/amd64
    ports:
      - '1883:1883'
    environment:
      USERNAME: '${MQTT_USERNAME}'
      PASSWORD: '${MQTT_PASSWORD}'
  auth:
    hostname: auth
    image: demo-system-auth:latest
    platform: linux/amd64
    ports:
      - '8000:8000'
    depends_on:
      - mqtt
    environment:
      MQTT_HOST: localhost
      MQTT_PORT: 1883
      MQTT_USERNAME: '${MQTT_USERNAME}'
      MQTT_PASSWORD: '${MQTT_PASSWORD}'
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
