version: '3.7'
services:
  api-module:
    hostname: api
    image: demo-system-api:latest
    # platform: linux/amd64
    ports:
      - '3001:3000'
    environment:
      IS_MICROSERVICE: true
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      GITHUB_CLIENT_ID: '${GITHUB_CLIENT_ID}'
      GITHUB_CLIENT_SECRET: '${GITHUB_CLIENT_SECRET}'
      AWS_ACCESS_KEY_ID_FOR_EMAIL: '${AWS_ACCESS_KEY_ID_FOR_EMAIL}'
      AWS_SECRET_ACCESS_KEY_FOR_EMAIL: '${AWS_SECRET_ACCESS_KEY_FOR_EMAIL}'
      SENDER_EMAIL: '${SENDER_EMAIL}'
      SNS_TOPIC_ARN: '${SNS_TOPIC_ARN}'
      DATABASE_URL: '${MONGODB_URL}'
      API_URL: '${API_URL}'
      PORTAL_URL: '${PORTAL_URL}'
      USER_MODULE_URL: 'user-module:5008'
      GENERATOR_MODULE_URL: 'generator-module:5002'
      DOCUMENT_MODULE_URL: 'document-module:5003'
      NODE_ENV: 'development'
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: testing
  #     POSTGRES_PASSWORD: testing
  #     POSTGRES_DB: default
  #   ports:
  #     - 5432:5432
  user-module:
    # depends_on:
      # - db
    image: demo-system-user-module:latest
    # platform: linux/amd64
    environment:
      CONNECTION_STRING: '${DB_CONNECTION_STRING}'
      ENABLE_GRPC_REFLECTION: true
    ports:
      - 5008:5008
  generator-module:
    image: demo-system-generator-module:latest
    platform: linux/amd64
    environment:
      REPLICATE_API_TOKEN: '${REPLICATE_API_TOKEN}'
      SCRIBBLE_MODEL: '${SCRIBBLE_MODEL}'
      BLIP_MODEL: '${BLIP_MODEL}'
    ports:
      - 5002:5002
  document-module:
    image: demo-system-document-module:latest
    platform: linux/amd64
    environment:
      DATABASE_URL: '${MONGODB_URL}'
    ports:
      - 5003:5003
