version: '3.7'
services:
  api-module:
    hostname: api
    image: demo-system-api:latest
    # platform: linux/amd64
    ports:
      - '3001:3000'
    environment:
      IS_MICROSERVICE: true
      MQTT_URL: mqtt://mqtt:1883
      MQTT_USERNAME: '${MQTT_USERNAME}'
      MQTT_PASSWORD: '${MQTT_PASSWORD}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      GITHUB_CLIENT_ID: '${GITHUB_CLIENT_ID}'
      GITHUB_CLIENT_SECRET: '${GITHUB_CLIENT_SECRET}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      SENDER_EMAIL: '${SENDER_EMAIL}'
      SNS_TOPIC_ARN: '${SNS_TOPIC_ARN}'
      DATABASE_URL: '${MONGODB_URL}'
      PORTAL_URL: '${PORTAL_URL}'
      SUB_SERVICE_PORT: 'sub:5008'
  mqtt:
    hostname: mqtt
    image: custom-mqtt-server:latest
    platform: linux/amd64
    ports:
      - '1883:1883'
    environment:
      USERNAME: '${MQTT_USERNAME}'
      PASSWORD: '${MQTT_PASSWORD}'
  auth:
    hostname: auth
    image: demo-system-auth:latest
    platform: linux/amd64
    ports:
      - '8000:8000'
    depends_on:
      - mqtt
    environment:
      MQTT_HOST: mqtt
      MQTT_PORT: 1883
      MQTT_USERNAME: '${MQTT_USERNAME}'
      MQTT_PASSWORD: '${MQTT_PASSWORD}'
      JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: default
    ports:
      - 5432:5432
  user-module:
    image: demo-system-user-module:latest
    # platform: linux/amd64
    environment:
      CONNECTION_STRING: '${DB_CONNECTION_STRING}'
      ENABLE_GRPC_REFLECTION: true
    ports:
      - 5008:5008
  generator-module:
    image: demo-system-generator-module:latest
    platform: linux/amd64
    environment:
      REPLICATE_API_TOKEN: '${REPLICATE_API_TOKEN}'
      REPLICATE_MODEL: '${REPLICATE_MODEL}'
    ports:
      - 5002:5002
  document-module:
    image: demo-system-document-module:latest
    platform: linux/amd64
    environment:
      DATABASE_URL: '${MONGODB_URL}'
    ports:
      - 5003:5003
